"""reference_material_column_correction

Revision ID: 9a51bc4ff76b
Revises: d5aa2fc70298
Create Date: 2025-08-24 16:31:50.278940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a51bc4ff76b"
down_revision: Union[str, Sequence[str], None] = "d5aa2fc70298"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reference_material",
        sa.Column(
            "reference_material_type",
            sa.Enum(
                "IMAGE",
                "TUTORIAL_VIDEO",
                "TUTORIAL_ARTICLE",
                "PROMPT",
                name="reference_material_type_enum",
            ),
            nullable=False,
        ),
    )
    op.drop_column("reference_material", "idea_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reference_material",
        sa.Column(
            "idea_type",
            postgresql.ENUM(
                "IMAGE",
                "TUTORIAL_VIDEO",
                "TUTORIAL_ARTICLE",
                "PROMPT",
                name="reference_material_type_enum",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("reference_material", "reference_material_type")
    # ### end Alembic commands ###
