"""create_art_ideas_table

Revision ID: e7ecceebd061
Revises: bc2132d2c46d
Create Date: 2025-08-14 21:45:57.872464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ecceebd061'
down_revision: Union[str, Sequence[str], None] = 'bc2132d2c46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier_name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('idea_type', sa.Enum('IMAGE', 'IMAGE_WITH_CAPTION', 'CAPTION_ONLY', name='idea_type'), nullable=False),
    sa.Column('inital_idea', sa.String(), nullable=True),
    sa.Column('final_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_name'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_idea')
    # ### end Alembic commands ###
