"""add_art_ideas_title

Revision ID: f793a0ca254f
Revises: e7ecceebd061
Create Date: 2025-08-20 14:55:02.425930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f793a0ca254f'
down_revision: Union[str, Sequence[str], None] = 'e7ecceebd061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_idea_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_type', sa.Enum('NOMINAL', 'PRIMARY', 'ALTERNATIVE', name='art_title_type'), nullable=False),
    sa.Column('title_text', sa.String(), nullable=False),
    sa.Column('art_idea_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['art_idea_id'], ['art_idea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_idea_title')
    # ### end Alembic commands ###
