"""reference material for art ideas

Revision ID: d5aa2fc70298
Revises: e8dd9038289b
Create Date: 2025-08-21 16:33:51.305052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5aa2fc70298"
down_revision: Union[str, Sequence[str], None] = "e8dd9038289b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_material",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "reference_material_type",
            sa.Enum(
                "IMAGE",
                "TUTORIAL_VIDEO",
                "TUTORIAL_ARTICLE",
                "PROMPT",
                name="reference_material_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "art_idea_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("art_idea_id", sa.Integer(), nullable=False),
        sa.Column("reference_material_id", sa.Integer(), nullable=False),
        sa.Column("reference_usage", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["art_idea_id"],
            ["art_idea.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_material_id"],
            ["reference_material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reference_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "storage_type",
            sa.Enum("LOCAL_DISK", "URL_LINK", name="storage_type_enum"),
            nullable=False,
        ),
        sa.Column("storage_link", sa.String(), nullable=False),
        sa.Column("reference_material_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reference_material_id"],
            ["reference_material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reference_storage")
    op.drop_table("art_idea_references")
    op.drop_table("reference_material")
    # ### end Alembic commands ###
